# Change these first
owner: xyz-Infrastructure # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: xyzscape
    url: https://xyzscape.xyz
  - name: xyzuan
    url: https://ceo.xyzscape.xyz
  - name: xdroid
    url: https://xd.xyzscape.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.xyzscape.xyz
  # baseUrl: /
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: xyzscape° infrastructure
  introTitle: "**xyzscape** is the most leading open-source contributor made by the broader developer community ."
  introMessage: This is status of our infrastructure which uses **real-time** data from our [GitHub repository](https://github.com/xyz-Infrastructure/status). 
  navbar:
    - title: Status
      href: /
    - title: xyz-prjkt
      href: https://github.com/xyz-prjkt
    - title: xdroid
      href: https://github.com/xdroid
    - title: xyzuan
      href: https://github.com/xyzuan

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
